import { Toaster } from "react-hot-toast";

import "./globals.css";

import { Montserrat, Outfit, Roboto } from "next/font/google";
import ScreenContextProvider from "../../lib/context-providers/screen-context";
import ActiveSectionContextProvider from "../../lib/context-providers/active-section-context";
import SkillsetContextProvider from "../../lib/context-providers/skillset-context";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});
<link rel="preload" href="/new-images/bg/BG16.jpg" as="image" />;

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lukes Folio",
  description: "Generated by Luke",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth bg-black">
      <body
        className={`bg-black overflow-x-hidden  ${montserrat.variable} ${outfit.variable} ${roboto.variable} relative`}
      >
        <div className=" text-gray-950   ">
          <Toaster position="top-right" />

          <div className="">
            <ScreenContextProvider>
              <ActiveSectionContextProvider>
                <SkillsetContextProvider>
                  {/* <Header /> */}
                  <div id="lightbox"></div>
                  {children}
                </SkillsetContextProvider>
              </ActiveSectionContextProvider>
            </ScreenContextProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
