import { Toaster } from "react-hot-toast";

import ActiveSectionContextProvider from "../../context/active-section-context";
import "./globals.css";

import { Montserrat, Outfit, Roboto } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});
<link rel="preload" href="/new-images/bg/BG15.jpg" as="image" />;
import AudioContextProvider from "../../context/screen-context";

import SkillsetContextProvider from "../../context/skillset-context";
import ScreenContextProvider from "../../context/screen-context";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lukes Folio",
  description: "Generated by Luke",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`bg-black overflow-x-hidden  ${montserrat.variable} ${outfit.variable} ${roboto.variable} relative`}
      >
        <div className=" text-gray-950   ">
          <Toaster position="top-right" />

          <div className="">
            <ScreenContextProvider>
              <ActiveSectionContextProvider>
                <SkillsetContextProvider>
                  {/* <Header /> */}
                  <div id="lightbox"></div>
                  {children}
                  {/* <Footer /> */}
                </SkillsetContextProvider>
              </ActiveSectionContextProvider>
            </ScreenContextProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
